---
name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches: [master]
env:
  IMAGE_NAME: ave-build
jobs:
  push-ghcr:
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Generate Image Version
        run: echo IMAGE_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |-
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
